version: '3.8'
services:
  web:
    build:
      context: .
    command: sh compose-run.sh
    volumes:
      - .:/app

  nginx:
    build: ./conf/nginx
    ports:
      - 80:80
    depends_on:
      - web